### ISSUE TITLE
Http(s) support for open file

### ISSUE THREAD

**Issue by ssaaiidd** [openspout/openspout#120]
Hello,

I can't read files transmitted via http(s) protocol. Because file_exists and is_readable don't support http(s) protocol, it gets stuck in validation in the open method. Do you have a solution for this? Removing the validation may not be the right way, developing an alternative validation may be the solution.

https://github.com/openspout/openspout/blob/cbf753126f43095112a099eff23ba4f0a47245eb/src/Reader/AbstractReader.php#L35-L43

https://www.php.net/manual/en/wrappers.php

Error log:
```
[2022-12-18 22:28:04] local.ERROR: Could not open https://support.staffbase.com/hc/en-us/article_attachments/360009197031/username.csv for reading! File does not exist. {"exception":"[object]
[stacktrace]                                                                                                                                                                                   
#0 /var/www/vendor/spatie/simple-excel/src/SimpleExcelReader.php(309): OpenSpout\\Reader\\AbstractReader->open('https://support...')                                                           
#1 /var/www/vendor/spatie/simple-excel/src/SimpleExcelReader.php(165): Spatie\\SimpleExcel\\SimpleExcelReader->getSheet()                                                                      
#2 /var/www/app/Services/API/Partners/Inone/ProductListService.php(240): Spatie\\SimpleExcel\\SimpleExcelReader->getRows()
```

**Comment by Slamdunk** [comment]
Any PR is welcome, although I suggest to just download the file locally first, and then proceed to analyse it

**Comment by ssaaiidd** [comment]
I'm temporarily downloading and processing the file right now. 

I did a small research about file_exists and is_readable. Only protocols `rar://`, `phar://` and `file://` support both file_exists and is_readable functions. Others don't support both (at least one). With isPhpStream, files aren't checked in the `php://` protocol. I think we don't need to file checks on all streams, not just php stream. If that sounds okay, I'll open a PR with I remove the file_exists and is_readable checks.

**Comment by Slamdunk** [comment]
I've just re-read the source, and stream wrapper are disable on purpose on both ODS and XLSX:

https://github.com/openspout/openspout/blob/cbf753126f43095112a099eff23ba4f0a47245eb/src/Reader/AbstractReader.php#L31-L33

https://github.com/openspout/openspout/blob/c130bc9a4b4e6d754d779775abab7abc5e89f9de/src/Reader/ODS/Reader.php#L40-L43

https://github.com/openspout/openspout/blob/c130bc9a4b4e6d754d779775abab7abc5e89f9de/src/Reader/XLSX/Reader.php#L58-L61

`isPhpStream` has nothing to do with wrappers and it's ok to check `file_exists` and `is_readable` there.

I have no idea why wrappers have been disabled in the past, I guess they won't work because `ODS` and `XLSX` are zip themselves and this library already uses streams to open the zip without unzipping the original file.

But if you are really into this, good tests are mandary though, so please propose a PR that:

1. Tests a regular file and read the `file://` stream
1. Tests a regular file and read the `http://` stream with the help of PHP built-in web server: start it with something like `php -S localhost:8080 -t path/to/regular/file/` and the stream should be `http://localhost:8080/myfile.xyz`
1. Do everything for `ODS`, `XLSX` and `CSV`
